[package]
name = "Alkahest"
version = "0.0.1"
edition = "2021"
default-run = "Alkahest"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vtable = "0.1.7"