[package]
name = "Alkahest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
substring = "1.4.5"
rand = "0.8.5"